# Generated by Django 5.2.4 on 2025-08-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default=''),
        ),
    ]
