# Generated by Django 5.2.4 on 2025-08-08 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewingdata',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='wrappedresult',
            name='upload',
        ),
        migrations.CreateModel(
            name='ViewingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='ViewingData',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.DeleteModel(
            name='WrappedResult',
        ),
    ]
