# Generated by Django 5.2.4 on 2025-08-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_upload_user_remove_viewingdata_upload_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViewingStats',
            new_name='ViewingStat',
        ),
    ]
