# Generated by Django 5.2.4 on 2025-08-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_viewingstats_viewingstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingstat',
            name='profile_name',
            field=models.CharField(default='unknown'),
            preserve_default=False,
        ),
    ]
