# Generated by Django 5.2.4 on 2026-05-24 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_viewingstat_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netflix_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(max_length=500, unique=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=50)),
                ('poster_url', models.URLField(blank=True, max_length=1000)),
                ('tmdb_id', models.CharField(blank=True, max_length=100)),
                ('omdb_id', models.CharField(blank=True, max_length=100)),
                ('metadata_source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized_name'], name='api_title_normali_d5871d_idx'), models.Index(fields=['media_type'], name='api_title_media_t_39a507_idx'), models.Index(fields=['rating'], name='api_title_rating_a4022a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_raw', models.CharField(max_length=1000)),
                ('started_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('device_type', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('supplemental_video_type', models.CharField(blank=True, max_length=255)),
                ('row_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_events', to='api.netflixprofile')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewing_events', to='api.title')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_events', to='api.upload')),
            ],
        ),
        migrations.AddIndex(
            model_name='netflixprofile',
            index=models.Index(fields=['user', 'name'], name='api_netflix_user_id_e5b03f_idx'),
        ),
        migrations.AddConstraint(
            model_name='netflixprofile',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_profile_per_user'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['user', 'uploaded_at'], name='api_upload_user_id_b61a81_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['status'], name='api_upload_status_070564_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['expires_at'], name='api_upload_expires_ae692d_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingevent',
            index=models.Index(fields=['profile', 'started_at'], name='api_viewing_profile_df9db6_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingevent',
            index=models.Index(fields=['title', 'started_at'], name='api_viewing_title_i_96c2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingevent',
            index=models.Index(fields=['upload'], name='api_viewing_upload__2a6f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingevent',
            index=models.Index(fields=['duration_seconds'], name='api_viewing_duratio_414f04_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingevent',
            index=models.Index(fields=['row_hash'], name='api_viewing_row_has_2135f2_idx'),
        ),
    ]
