# Generated by Django 5.2.4 on 2026-05-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_netflixprofile_title_upload_viewingevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewingStat',
        ),
    ]
