# Generated by Django 5.2.4 on 2026-06-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_yearlyrecap'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingevent',
            name='classification_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='viewingevent',
            name='classification_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='viewingevent',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewingevent',
            name='episode_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='viewingevent',
            name='is_episode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewingevent',
            name='parsed_media_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='viewingevent',
            name='season_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='viewingevent',
            name='series_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='viewingevent',
            index=models.Index(fields=['parsed_media_type'], name='api_viewing_parsed__3cb1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingevent',
            index=models.Index(fields=['is_episode'], name='api_viewing_is_epis_430473_idx'),
        ),
    ]
