# Generated by Django 5.2.4 on 2026-06-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_viewingevent_classification_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='canonical_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='title',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unknown', 'Unknown'), ('needs_review', 'Needs review')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='title',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='title',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='metadata_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='title',
            name='original_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='title',
            name='retry_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['enrichment_status'], name='api_title_enrichm_dd7130_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['last_enriched_at'], name='api_title_last_en_49f53c_idx'),
        ),
    ]
