# Generated by Django 5.2.4 on 2026-06-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_title_canonical_name_title_enrichment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='origin_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='title',
            name='original_language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='title',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
