# Generated by Django 5.2.4 on 2026-06-23 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_title_origin_countries_title_original_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCatalogTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='tmdb', max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('origin_countries', models.JSONField(blank=True, default=list)),
                ('original_language', models.CharField(blank=True, max_length=20)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=50)),
                ('popularity', models.FloatField(default=0)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('poster_url', models.URLField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'media_type'], name='api_externa_source_5aa27e_idx'), models.Index(fields=['last_refreshed_at'], name='api_externa_last_re_074efb_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'media_type', 'external_id'), name='unique_external_catalog_title')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('algorithm_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=20)),
                ('profile_summary', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_sets', to='api.netflixprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('segment', models.CharField(default='top_match', max_length=50)),
                ('explanation', models.CharField(max_length=500)),
                ('contributing_signals', models.JSONField(blank=True, default=dict)),
                ('catalog_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.externalcatalogtitle')),
                ('recommendation_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.recommendationset')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendationset',
            index=models.Index(fields=['profile', 'generated_at'], name='api_recomme_profile_cf96cc_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationset',
            index=models.Index(fields=['period_end', 'algorithm_version'], name='api_recomme_period__f38d81_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationset',
            constraint=models.UniqueConstraint(fields=('profile', 'period_start', 'period_end', 'algorithm_version'), name='unique_profile_recommendation_period'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('recommendation_set', 'catalog_title'), name='unique_title_per_recommendation_set'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('recommendation_set', 'rank'), name='unique_rank_per_recommendation_set'),
        ),
    ]
