# Generated by Django 5.2.4 on 2026-06-24 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_externalcatalogtitle_recommendationset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('looks_good', 'Looks good'), ('not_interested', 'Not interested'), ('already_watched', 'Already watched'), ('saved', 'Saved')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_feedback', to='api.externalcatalogtitle')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to='api.netflixprofile')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='api.recommendation')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'action'], name='api_recomme_profile_bd32db_idx'), models.Index(fields=['catalog_title', 'action'], name='api_recomme_catalog_3fb052_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'catalog_title'), name='unique_recommendation_feedback_per_profile_title')],
            },
        ),
    ]
